import type { Metadata } from 'next';
import './globals.css';
import { TodoProvider } from '@/contexts/TodoContext';
import NavList from '@/components/organisms/NavList';

export const metadata: Metadata = {
  title: 'nextjs output with api crud',
  description: 'Generated by nextjs output with api crud',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="container">
          <NavList />
          <TodoProvider>{children}</TodoProvider>
        </div>
      </body>
    </html>
  );
}
